export const LAYER_MEMORIAL = "MEMORIAL";
export const LAYER_ESTILOS_ALT = "ESTILOS";
export const LAYER_GUIAS_DELETAR = "GUIAS_DELETAR";
export const LAYER_GUIAS_ALT = "GUIAS";

/** @deprecated Use LAYER_ESTILOS_ALT */
export const LAYER_ESTILOS = LAYER_ESTILOS_ALT;
/** @deprecated Use LAYER_GUIAS_ALT */
export const LAYER_GUIAS = LAYER_GUIAS_ALT;

export const COLOR_CORPROF = "CorProf";
export const COLOR_GUIAS_DELETAR = "GUIAS_DELETAR";

/** @deprecated Use COLOR_GUIAS_DELETAR */
export const COLOR_GUIAS = "GUIAS";

export const SPOT_COLOR_EXCEPTIONS = [COLOR_CORPROF, COLOR_GUIAS_DELETAR];

export const ACCEPTED_LANGUAGES = ["Portuguese: Brazilian", "Português: Brasileiro"];

export const MIN_IMAGE_DPI = 300;
export const MIN_STROKE_WEIGHT = 0.3;
export const BLEED_MM = 20;
export const PDF_PRESET_NAME = "CTP_Arte";
export const PDF_PRESET_FALLBACK_NAMES = ["CTP_Arte", "CTP Arte"] as const;
export const PACKAGE_FOLDER_NAME = "Package";

export const VALIDATOR_IDS = {
  LAYERS_OBRIGATORIAS: "V01_LAYERS_OBRIGATORIAS",
  LAYERS_NOMENCLATURA: "V02_LAYERS_NOMENCLATURA",
  MEMORIAL_DESCRITIVO: "V03_MEMORIAL_DESCRITIVO",
  CORES: "V04_CORES",
  CORPROF: "V06_CORPROF",
  GUIAS_COLOR: "V07_GUIAS_COLOR",
  OVERPRINT: "V08_OVERPRINT",
  ESTILOS_IDIOMA: "V09_ESTILOS_IDIOMA",
  HIFENIZACAO: "V10_HIFENIZACAO",
  ESTILOS_NOMENCLATURA: "V11_ESTILOS_NOMENCLATURA",
  FONTES: "V12_FONTES",
  FONTES_DUPLICADAS: "V13_FONTES_DUPLICADAS",
  LINKS: "V14_LINKS",
  IMAGENS_COLORSPACE: "V15_IMAGENS_COLORSPACE",
  RESOLUCAO: "V16_RESOLUCAO",
  FIOS: "V17_FIOS",
  PASTEBOARD: "V18_PASTEBOARD",
  LAYERS_BLOQUEADAS: "V19_LAYERS_BLOQUEADAS",
  OVERTEXT: "V21_OVERTEXT",
} as const;
